#!/bin/bash

yum install -y curl wget gcc-c++ make vim dnf epel-release dnf-plugins-core cockpit cockpit-{packagekit,sosreport,storaged,networkmanager,selinux,kdump}
dnf install -y https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.8/cockpit-navigator-0.5.8-1.el8.noarch.rpm
systemctl enable --now cockpit.socket && systemctl start cockpit.socket
#curl -s https://install.speedtest.net/app/cli/install.rpm.sh | sudo bash
dnf -y install https://pkgs.dyn.su/el8/base/x86_64/raven-release-1.0-2.el8.noarch.rpm
dnf -y config-manager --set-enabled {raven,raven-extras,powertools,epel,extras,plus}
dnf -y update && dnf -y upgrade
curl -sL https://rpm.nodesource.com/setup_17.x | sudo -E bash -
dnf -y install git nodejs neofetch zsh python2 python36
sudo alternatives --set python /usr/bin/python3
#dnf -y --enablerepo=powertools install fuse-sshfs
npm i -g typescript pm2
sed -i 's/bash/zsh/g' /etc/default/useradd
usermod --shell /bin/zsh root
cd ~
sh -c "$(curl -fsSL https://raw.github.com/datflowts/centosinit/master/zshinit-w)"
