#!/bin/bash

yum install -y curl wget gcc-c++ make vim dnf dnf-plugins-core cockpit && \ #some hosters deploy Fedora images withoug Cockpit 
systemctl enable --now cockpit.socket && systemctl start cockpit.socket && \
wget https://bintray.com/ookla/rhel/rpm -O bintray-ookla-rhel.repo && \
sudo mv bintray-ookla-rhel.repo /etc/yum.repos.d/ && \
dnf -y update && dnf -y upgrade && \
curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash - && \
dnf -y install git nodejs neofetch zsh python2 python36 speedtest && \
alternatives --set python /usr/bin/python3 && \
dnf -y --enablerepo=powertools install fuse-sshfs && \
npm i -g typescript pm2 && \
sed -i 's/bash/zsh/g' /etc/default/useradd && \
usermod --shell /bin/zsh root && \
cd ~ && \
sh -c "$(curl -fsSL https://raw.github.com/datflowts/centosinit/master/zshinit-w)"
