#!/bin/bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" && \
brew update && \
brew install wget vim git neofetch && \
touch ~/.zshrc && \
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh && \
sed -i'' -e 's/RUNZSH=\${RUNZSH:-yes}/RUNZSH=\${RUNZSH:-no}/g' install.sh && \
sed -i'' -e 's/RUNZSH=yes/RUNZSH=no/g' install.sh && \
sh install.sh && \
rm -rfv install.sh && \
sed -i'' -e 's/robbyrussell/agnoster/g' $HOME/.zshrc && \
sed -i'' -e '6i\'$'\n''neofetch' .zshrc && \
source $HOME/.zshrc && \
compaudit | xargs chmod g-w,o-w %% \
mkdir $HOME/.ssh && \
touch $HOME/.ssh/authorized_keys && \
curl -fsSL https://share.datflow.tech/LNXScrpts/.ssh/authorized_keys > $HOME/.ssh/authorized_keys && \
cd /usr/local/bin && \
wget https://share.datflow.tech/LNXScrpts/bash-login && \
/bin/zsh -c "$(curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh)" && \
export NVM_DIR="$HOME/.nvm" && \
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  && \
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  && \
nvm install node && \
npm i -g typescript pm2 && \
mkdir $HOME/Library/LaunchAgents && \
touch $HOME/Library/LaunchAgents/pm2.$USER.plist && \
sudo env PATH=$PATH:$HOME/.nvm/versions/node/v15.7.0/bin $HOME/.nvm/versions/node/v15.7.0/lib/node_modules/pm2/bin/pm2 startup launchd -u $USER --hp $HOME && \
echo "-----------------------------" && \
echo "-----------------------------" && \
echo "-----------------------------" && \
echo "Finished! Reboot recommended!"
