#!/bin/zsh

apt update && apt install -y vim wget host pigz samba samba-common smbclient cifs-utils mysql-server && \
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.1:/stable/xUbuntu_18.04/ /" > /etc/apt/sources.list.d/opsi.list && \
wget -nv https://download.opensuse.org/repositories/home:uibmz:opsi:4.1:stable/xUbuntu_18.04/Release.key -O Release.key && \
apt-key add - < Release.key && \
apt update && \
apt install opsi-tftpd-hpa opsi-server opsi-windows-support && \
vim /etc/mysql/mysql.conf.d/mysqld.cnf && \
systemctl restart mysql.service && \
vim /etc/hosts && \
opsi-setup --configure-mysql && \
vim /etc/opsi/backendManager/dispatch.conf && \
opsi-setup --init-current-config && \
opsi-set-rights && \
systemctl restart opsiconfd.service && \
systemctl restart opsipxeconfd.service && \
opsi-setup --auto-configure-samba && \
systemctl restart smbd.service && \
systemctl restart nmbd.service && \
opsi-admin -d task setPcpatchPassword && \
smbpasswd -a opsi && \
usermod -aG opsiadmin opsi && \
usermod -aG pcpatch opsi && \
opsi-setup --patch-sudoers-file && \
apt update && apt upgrade -y && \
apt remove isc-dhcp-server && apt purge isc-dhcp-server && \
opsi-set-rights /var/lib/opsi/repository && \
cd /var/lib/opsi/repository && \
wget https://download.uib.de/opsi4.1/stable/packages/windows/netboot/opsi-clonezilla_4.1.0.2-1.opsi && \
opsi-package-manager --install /var/lib/opsi/repository/*.opsi && \
opsi-package-updater -v install && opsi-package-updater -v update && \
reboot
