#!/bin/bash

export LOGFILE="$HOME/init_$(date +%F).log"

dnf -y install https://pkgs.dyn.su/el9/base/x86_64/raven-release-1.0-4.el9.noarch.rpm 2>&1 | tee -a $LOGFILE
dnf -y config-manager --set-enabled {crb,baseos,appstream,extras,plus,raven,raven-{extras,modular,multimedia}} 2>&1 | tee -a $LOGFILE
dnf -y install epel-release dnf-plugins-core gcc-c++ 2>&1 | tee -a $LOGFILE
dnf -y config-manager --set-enabled epel-release
dnf -y install https://rpms.remirepo.net/enterprise/remi-release-9.rpm 2>&1 | tee -a $LOGFILE
dnf -y upgrade --refresh 2>&1 | tee -a $LOGFILE
dnf -y update 2>&1 | tee -a $LOGFILE
dnf -y install wget make vim cockpit cockpit-{packagekit,sosreport,storaged,networkmanager,selinux,kdump} 2>&1 | tee -a $LOGFILE
dnf -y install https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator-0.5.10-1.el8.noarch.rpm 2>&1 | tee -a $LOGFILE
systemctl enable --now cockpit.socket 2>&1 | tee -a $LOGFILE
curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.rpm.sh | sudo bash 2>&1 | tee -a $LOGFILE
curl -sL https://rpm.nodesource.com/setup_current.x | sudo -E bash - 2>&1 | tee -a $LOGFILE
systemctl daemon-reload 2>&1 | tee -a $LOGFILE
sudo curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o /usr/bin/neofetch 2>&1 | tee -a $LOGFILE
chmod -v 555 /usr/bin/neofetch 2>&1 | tee -a $LOGFILE
dnf -y upgrade --refresh --best 2>&1 | tee -a $LOGFILE
dnf -y update 2>&1 | tee -a $LOGFILE
dnf -y install git fuse-sshfs nodejs zsh python2 python36 speedtest 2>&1 | tee -a $LOGFILE
sudo alternatives --set python /usr/bin/python3 2>&1 | tee -a $LOGFILE
npm i -g npm 2>&1 | tee -a $LOGFILE
npm i -g typescript pm2 2>&1 | tee -a $LOGFILE
sed -i 's/bash/zsh/g' /etc/default/useradd
usermod --shell /bin/zsh root 2>&1 | tee -a $LOGFILE
echo "
--------------------------
--------------------------
" 2>&1 | tee -a $LOGFILE
echo "
Disable 'root' login for SSH?
(Y/N, default N):
" 2>&1 | tee -a $LOGFILE
read -s -r -n 1 YNROOT
if [[ $YNROOT =~ ^[Yy]$ ]]; then
    sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
    sed -i 's/#PermitRootLogin/PermitRootLogin/g' /etc/ssh/sshd_config
    echo "
You answered: YES
--------------------------
SSH Acces for 'root' has been disabled.
" 2>&1 | tee -a $LOGFILE
else
    echo "
You answered: NO
--------------------------
Kept current configuration. Proceeding to next step.
WARNING: it's not recommended to grant SSH access for 'root'!
--------------------------
" 2>&1 | tee -a $LOGFILE
fi
echo "
--------------------------
--------------------------
" 2>&1 | tee -a $LOGFILE
echo "
Disable password authentication for SSH?
(Y/N, default N):
" 2>&1 | tee -a $LOGFILE
read -s -r -n 1 YNPWAUTH
if [[ $YNPWAUTH =~ ^[Yy]$ ]]; then
    sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
    sed -i 's/#PasswordAuthentication/PasswordAuthentication/g' /etc/ssh/sshd_config
    echo "
You answered: YES
--------------------------
Password authentication for SSH has been disabled.
" 2>&1 | tee -a $LOGFILE
else
    echo "
You answered: NO
--------------------------
Kept current configuration. Proceeding to next steps.
WARNING: it's recommended to authenticate via ssh-key instead!
--------------------------
" 2>&1 | tee -a $LOGFILE
fi
cd ~
sh -c "$(curl -fsSL https://raw.github.com/datflowts/centosinit/master/zshinit-w)"
