#!/bin/bash

export LOGFILE="$HOME/init_$(date +%F).log"

yum install -y curl wget gcc-c++ make vim dnf epel-release dnf-plugins-core cockpit cockpit-{packagekit,sosreport,storaged,networkmanager,selinux,kdump} &>> $LOGFILE
dnf install -y https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.8/cockpit-navigator-0.5.8-1.el8.noarch.rpm &>> $LOGFILE
systemctl enable --now cockpit.socket &>> $LOGFILE
mkdir install;cd install
wget https://install.speedtest.net/app/cli/ookla-speedtest-1.1.1-linux-x86_64.tgz &>> $LOGFILE
tar -xvf ookla-speedtest-1.1.1-linux-x86_64.tgz &>> $LOGFILE
chmod 555 speedtest;cp speedtest /usr/local/bin/ &>> $LOGFILE
cd ..;rm -r install
dnf -y install https://pkgs.dyn.su/el8/base/x86_64/raven-release-1.0-2.el8.noarch.rpm &>> $LOGFILE
dnf -y config-manager --set-enabled {raven,raven-{extras,modular,multimedia},powertools,epel,epel-modular,extras,plus} &>> $LOGFILE
curl -sL https://rpm.nodesource.com/setup_17.x | sudo -E bash - &>> $LOGFILE
sed -i '/priority/d' /etc/yum.repos.d/nodesource-el8.repo &>> $LOGFILE
systemctl daemon-reload
dnf -y upgrade --refresh --best &>> $LOGFILE
sudo curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o /usr/bin/neofetch &>> $LOGFILE
chmod 555 /usr/bin/neofetch
dnf -y install git fuse-sshfs nodejs zsh python2 python36 &>> $LOGFILE
sudo alternatives --set python /usr/bin/python3 &>> $LOGFILE
npm i -g npm
npm i -g typescript pm2 &>> $LOGFILE
sed -i 's/bash/zsh/g' /etc/default/useradd
usermod --shell /bin/zsh root
read -p "Disable root login and password auth for SSH? (Y/N, default N) => " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
    sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
    sed -i 's/#PasswordAuthentication/PasswordAuthentication/g' /etc/ssh/sshd_config
    sed -i 's/#PermitRootLogin/PermitRootLogin/g' /etc/ssh/sshd_config
else
    echo "Kept current configuration. Proceeding to next steps."
fi
cd ~
sh -c "$(curl -fsSL https://raw.github.com/datflowts/centosinit/master/zshinit-w)"