#!/bin/bash

apt -y update && apt -y upgrade && \
apt install -y curl wget gcc make vim sshfs gnupg1 apt-transport-https dirmngr && \
export INSTALL_KEY=379CE192D401AB61 && \
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $INSTALL_KEY && \
curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash && \
curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash - && \
apt update && \
apt -y install git nodejs neofetch zsh speedtest && \
npm i -g typescript pm2 && \
sed -i 's/bash/zsh/g' /etc/adduser.conf && \
sed -i 's/sh/zsh/g' /etc/default/useradd && \
sed -i 's/\# GROUP=100/GROUP=100/g' /etc/default/useradd && \
sed -i 's/# HOME=\/home/HOME=\/home\/users/g' /etc/default/useradd && \
sed -i 's/\# SKEL=\/etc\/skel/SKEL=\/etc\/skel/g' /etc/default/useradd && \
sed -i 's/\# CREATE_MAIL_SPOOL=yes/CREATE_MAIL_SPOOL=yes/g' /etc/default/useradd && \
sed -i 's/\/home/\/home\/users/g' /etc/adduser.conf && \
usermod --shell /bin/zsh root && \
cd ~ && \
sh -c "$(curl -fsSL https://raw.github.com/datflowts/centosinit/master/zshinit-r)"
