#!/bin/zsh

wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh && \
sed -i 's/RUNZSH=\${RUNZSH:-yes}/RUNZSH=\${RUNZSH:-no}/g' install.sh && \
sed -i 's/RUNZSH=yes/RUNZSH=no/g' install.sh && \
sh install.sh && \
rm -rfv install.sh && \
sed -i 's/robbyrussell/agnoster/g' $HOME/.zshrc && \
sed -i 's/\/root/\$HOME/g' $HOME/.zshrc && \
sed -i '7i neofetch' .zshrc && \
cp -rfv $HOME/.*zsh* /etc/skel/ && \
mkdir /etc/skel/.ssh && \
curl -fsSL https://paste.datflow.tech/2020/08/id_rsa.pub.txt >> /etc/skel/.ssh/authorized_keys && \
curl -fsSL https://paste.datflow.tech/2020/08/id_rsa.pub.txt >> /root/.ssh/authorized_keys && \
cd /usr/local/bin && \
wget https://share.datflow.tech/2020/08/bash-login && \
cd ~ && \
chmod -v 555 /usr/local/bin/** &&\
touch .hushlogin && \
touch /etc/skel/.hushlogin && \
useradd datflow && \
usermod -aG wheel datflow && \
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u datflow --hp /home/datflow && \
pm2 startup && \
echo "Set Password for DatFlow:" && \
passwd datflow && \
echo "-----------------------------" && \
echo "-----------------------------" && \
echo "-----------------------------" && \
echo "Finished! Reboot recommended!"
