#!/bin/zsh

rm -rf /root/.*zsh* /etc/skel/.*ssh* /etc/skel/.*zsh*
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
sed -i 's/RUNZSH=\${RUNZSH:-yes}/RUNZSH=\${RUNZSH:-no}/g' install.sh
sed -i 's/RUNZSH=yes/RUNZSH=no/g' install.sh
sh install.sh
rm -rfv install.sh
sed -i 's/robbyrussell/agnoster/g' $HOME/.zshrc
sed -i 's/\/root/\$HOME/g' $HOME/.zshrc
echo "" >> $HOME/.zshrc
echo "############################################" >> $HOME/.zshrc
echo "############################################" >> $HOME/.zshrc
echo "" >> $HOME/.zshrc
echo "# some customizations following here" >> $HOME/.zshrc
echo 'export PATH="$HOME/sbin:$HOME/.local/sbin:$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:$PATH"' >> $HOME/.zshrc
echo 'neofetch' >> $HOME/.zshrc
echo "alias clear='clear;neofetch'" >> $HOME/.zshrc
cp -afv $HOME/.*zsh* /etc/skel/
cp -afv $HOME/.*ssh* /etc/skel/
cp -afv $HOME/.*zsh* /home/clashi/
cp -afv $HOME/.*ssh* /home/clashi/
chown -R clashi:clashi /home/clashi
cd /usr/local/bin
echo "apt autoclean && apt update && apt upgrade" >> ./update
cd ~
chmod -v 555 /usr/local/bin/** &&\
touch .hushlogin
touch /etc/skel/.hushlogin
env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u clashi --hp /home/clashi
pm2 startup
echo "-----------------------------"
echo "Now we're checking your connection! Please accept with 'yes'!"
echo "-----------------------------"
speedtest
echo "-----------------------------"
echo "-----------------------------"
echo "-----------------------------"
echo "Finished! Reboot recommended!"
