#!/bin/zsh

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
sed -i 's/robbyrussell/agnoster/g' $HOME/.zshrc && \
sed -i 's/\/root/\$HOME/g' $HOME/.zshrc && \
sed -i '7i neofetch' .zshrc && \
cp -rfv $HOME/.*zsh* /etc/skel/
