#!/bin/zsh

rm -rf $HOME/.*ssh* $HOME/.*zsh* /etc/skel/.*ssh* /etc/skel/.*zsh* >> /dev/null
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh >> /dev/null
sed -i 's/RUNZSH=\${RUNZSH:-yes}/RUNZSH=\${RUNZSH:-no}/g' install.sh
sed -i 's/RUNZSH=yes/RUNZSH=no/g' install.sh
sed -i '352,360d' install.sh
sh install.sh >> /dev/null
rm -f install.sh
sed -i 's/robbyrussell/agnoster/g' $HOME/.zshrc
sed -i 's/\/root/\$HOME/g' $HOME/.zshrc
echo "" >> $HOME/.zshrc
echo "############################################" >> $HOME/.zshrc
echo "############################################" >> $HOME/.zshrc
echo "" >> $HOME/.zshrc
echo "# some customizations following here" >> $HOME/.zshrc
echo 'export PATH="$HOME/sbin:$HOME/.local/sbin:$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:$PATH"' >> $HOME/.zshrc
echo 'neofetch' >> $HOME/.zshrc
echo "alias clear='clear;neofetch'" >> $HOME/.zshrc
cp -afv $HOME/.*zsh* /etc/skel/ >> /dev/null
mkdir $HOME/.ssh;cd $HOME/.ssh
curl https://github.com/datflowts.keys | tee -a authorized_keys >> /dev/null
cp -afv $HOME/.*ssh* /etc/skel/ >> /dev/null
cd /usr/local/bin
echo "#\!/bin/zsh" > update
echo "" >> update
echo "# Optionally you can pass an argument for dnf, e.g. 'sudo update --nobest'" >> update
echo 'dnf -y upgrade --refresh $@ >> /dev/null;dnf clean all >> /dev/null' >> update
echo 'echo "Finished! Your system is up2date now! Reboot recommended."' >> update
cd ~
git clone https://github.com/powerline/fonts.git --depth=1 >> /dev/null
cd fonts
./install.sh >> /dev/null
cd ..
rm -rf fonts
cp -afv $HOME/.local /etc/skel/ >> /dev/null
chmod -v 555 /usr/local/bin/**
touch .hushlogin
touch /etc/skel/.hushlogin
echo '#############################################################'
echo '#############################################################'
echo '#############################################################'
echo "How should the username of the default user (with sudo privileges) be?"
echo
read USRNAME
LOCK=0
while [[ "$LOCK" -eq "0" ]]; do
    if [[ "$USRNAME" =~ ^([0-9]{0,31}[[:lower:]]{1,32}[0-9]{0,31}){1,32}$ ]]; then
        if [[ "$USRNAME" == "default" ]] | [[ "$USRNAME" == "cancel" ]]; then
            $USRNAME = 'default0'
        fi
        LOCK=1
    else
        echo "Please provide a valid unix username:"
        echo " - only 1-32 lowercase alphanumeric characters allowed"
        echo " - at least one letter is required"
        echo "Try again or type 'cancel'/'default' to cancel and proceed with the script"
        echo "Then, a user named 'default0' would be created"
        read USRNAME
        LOCK=0
    fi
done
export NEWUSER=$USRNAME
useradd $USRNAME
echo "User '$NEWUSER' successfully created!"
usermod -aG wheel $USRNAME
env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u $USRNAME --hp /home/$USRNAME >> /dev/null
pm2 startup >> /dev/null
echo '#############################################################'
echo '#############################################################'
echo '#############################################################'
echo
echo "No we're checking your connection! Please accept with 'yes'!"
echo
echo '#############################################################'
echo '#############################################################'
echo '#############################################################'
speedtest
read -p "Install KDE Plasma Desktop, too? (Y/N, default N) => " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sh -c "$(curl -fsSL https://raw.github.com/datflowts/centosinit/master/rockykde)"
fi
update '--best --skip-broken --allowerasing' >> /dev/null
echo '#############################################################'
echo '#############################################################'
echo '#############################################################'
echo
echo "Finished! Reboot recommended!"